using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.SqlClient;
namespace DataFrame
{
    public class Map<T>
    {
        static string connectionString;
        public Map(string Connection)
        {
            connectionString = Connection;
        }

        public void CreateTable()
        {
            CreateDataBase("DataFrameAutoGenerated");
            CreateCommand($"Create table {typeof(T).Name}",false);
            var Comando = "";
            foreach (System.Reflection.PropertyInfo prop in typeof(T).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))
            {
                if (prop.PropertyType == typeof(string))
                {
                    Comando += "create ";
                }
                else if (prop.PropertyType == typeof(int))
                {
                    Console.WriteLine("Create a int");
                }

            }
        }


        private static bool CreateCommand(string queryString, bool IsDB)
        {
            using (SqlConnection connection = new SqlConnection(
                       connectionString))
            {
                SqlCommand command = new SqlCommand(queryString, connection);
                command.Connection.Open();
                int r = -1;
                if (IsDB)
                {
                    r = (int)command.ExecuteScalar();

                }
                else {
                    r = command.ExecuteNonQuery();
                }
                return r != 1 ? true : false;
            }
        }
        public void CreateDataBase(string NomeBanco)
        {
            //  var Check = "select name from master.sys.databases where name = '" + NomeBanco + "'";  
            var Check = "SELECT top 1 COUNT(*) FROM sys.databases where name = 'Teste'";
            if (CreateCommand(Check,true))
            {
                CreateCommand("CREATE DATABASE " + NomeBanco, false);
            }
        }

        public void Testar()
        {
            CreateDataBase("Teste");
            CreateCommand($"Create table {typeof(T).Name} (" +
                $"id int, nome nvarchar(100), primary key (id) " +
                $");", false);
        }

    }
}
